# Generated by Django 5.2.13 on 2026-04-16 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('summary', models.TextField()),
                ('status', models.CharField(default='draft', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('department_head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports', to='scholarships.departmentheadprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_reports', to='academic.term')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
