# Generated by Django 5.2.13 on 2026-04-16 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(max_length=20)),
                ('periods_per_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('sequence_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academic.studyplan')),
            ],
            options={
                'ordering': ['-academic_year', 'sequence_number'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'study_plan', 'sequence_number'), name='uniq_academic_term_per_plan_sequence'), models.CheckConstraint(condition=models.Q(('start_date__lte', models.F('end_date'))), name='term_dates_valid')],
            },
        ),
    ]
