# Generated by Django 5.2.13 on 2026-04-16 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hours', '0001_initial'),
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('hours_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hours.hourslog')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='scholarships.departmentheadprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
