# Generated by Django 5.2.13 on 2026-04-16 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentHeadProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('career', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='department_head_profile', to='academic.career')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='department_head_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student_code', models.SlugField(max_length=30, unique=True)),
                ('admission_year', models.PositiveSmallIntegerField()),
                ('scholarship_status', models.CharField(default='active', max_length=30)),
                ('required_annual_hours', models.PositiveIntegerField(default=150)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.career')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.studyplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_code'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee_code', models.SlugField(blank=True, max_length=30, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('subarea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='organization.subarea')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='academic.term')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scholarships.student')),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='scholarships.teacherprofile')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'term'), name='uniq_active_assignment_per_student_term')],
            },
        ),
    ]
