# Generated by Django 5.2.13 on 2026-04-16 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('scholarships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoursLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reported_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('status', models.CharField(default='registered', max_length=30)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours_logs', to='scholarships.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours_logs', to='scholarships.student')),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours_logs', to='scholarships.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hours_logs', to='academic.term')),
            ],
            options={
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoursEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_url', models.CharField(max_length=500)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
                ('hours_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='hours.hourslog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoursPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('annual_target_hours', models.PositiveIntegerField(default=150)),
                ('is_active', models.BooleanField(default=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='HoursPolicySegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_sequence', models.PositiveSmallIntegerField()),
                ('target_hours', models.PositiveIntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='hours.hourspolicy')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_segments', to='academic.studyplan')),
            ],
            options={
                'ordering': ['policy', 'study_plan', 'period_sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='hourslog',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='hours_time_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='hourslog',
            constraint=models.CheckConstraint(condition=models.Q(('reported_hours__gt', 0)), name='hours_reported_positive'),
        ),
        migrations.AddConstraint(
            model_name='hourspolicy',
            constraint=models.UniqueConstraint(fields=('name', 'version'), name='uniq_policy_name_version'),
        ),
        migrations.AddConstraint(
            model_name='hourspolicy',
            constraint=models.CheckConstraint(condition=models.Q(('annual_target_hours__gt', 0)), name='policy_target_positive'),
        ),
        migrations.AddConstraint(
            model_name='hourspolicy',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='policy_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='hourspolicysegment',
            constraint=models.UniqueConstraint(fields=('policy', 'study_plan', 'period_sequence'), name='uniq_policy_plan_period'),
        ),
        migrations.AddConstraint(
            model_name='hourspolicysegment',
            constraint=models.CheckConstraint(condition=models.Q(('target_hours__gte', 0)), name='policy_segment_non_negative'),
        ),
    ]
